name: checkout_test
on: workflow_dispatch

jobs:
  no-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: try to read file
        run: cat ./README.md

  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: try to read file
        run: cat ./README.md