name: needs
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo job1 done
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - name: echo
        run: echo job2 done
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "job3 start"
          exit 1
  job4:
    runs-on: ubuntu-latest
    needs: [job3]
    if: ${{ always() }}
    steps:
      - name: echo
        run: echo job4 after job3