name: workflow_dispatch

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'set name'
        required: true
        default: 'github-actions'
        type: string
      environment:
        description: 'set env'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  workflow_dispatch-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1 echo hello world
        run: echo "hello world!"

      - name: step2 echo github action
        run: |
          echo "hello world!"
          echo "github action!"

      - name: echo input
        run: |
          echo "NAME: ${{ inputs.name }}"
          echo "ENVIRONMENT: ${{ inputs.environment }}"
