name: environment

on: push

jobs:
  get-env:
    runs-on: ubuntu-latest

    steps:
      - name: check env & secret org
        run: |
          echo "LEVEL: ${{ vars.LEVEL }}"
          echo "KEY: ${{ secrets.KEY }}"